# for more information see: https://docs.github.com/en/actions/tutorials/build-and-test-code/net#publishing-to-package-registries

name: Upload dotnet package

on:
  push:
    tags:
      - '*'
    #perhaps include tags like this (or maype that is for push?):
        #tags:
        #- "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/<owner>/index.json #this won't work until we figure out what to replace <owner> with, see: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry 
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        name: Build
      - run: dotnet build --no-restore
        name: Test
      - run: dotnet test --no-build --verbosity normal
        name: Releases
      - run : dotnet publish
